/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_AbstractPlainDatagramSocketImpl */

#ifndef _Included_java_net_AbstractPlainDatagramSocketImpl
#define _Included_java_net_AbstractPlainDatagramSocketImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_net_AbstractPlainDatagramSocketImpl
 * Method:    dataAvailable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_net_AbstractPlainDatagramSocketImpl_dataAvailable
  (JNIEnv *, jobject);

/*
 * Class:     java_net_AbstractPlainDatagramSocketImpl
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_net_AbstractPlainDatagramSocketImpl_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
