/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_net_ExtendedSocketOptions_ExtSocketOption */

#ifndef _Included_jdk_net_ExtendedSocketOptions_ExtSocketOption
#define _Included_jdk_net_ExtendedSocketOptions_ExtSocketOption
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
