package com.android.i18n;

import java.text.ParseException;
import java.util.ListResourceBundle;
import java.util.Locale;

/**
 * Pulls plural rules data from a ListResourceBundle generated by
 * "genrb -j ASCII ~/local-disk/aosp/external/icu4c/data/misc/plurals.txt".
 */
public class PluralRulesLoader {
  public static final PluralRulesLoader loader = new PluralRulesLoader();

  // Trivial single-locale cache.
  public Locale cachedLocale;
  public PluralRules cachedCardinalRules;
  public PluralRules cachedOrdinalRules;

  private PluralRulesLoader() {
  }

  public PluralRules forLocale(Locale locale, PluralRules.PluralType pluralType) {
    synchronized (this) {
      if (locale.equals(cachedLocale)) {
        return (pluralType == PluralRules.PluralType.CARDINAL ? cachedCardinalRules: cachedOrdinalRules);
      }

      cachedLocale = locale;
      cachedCardinalRules = makeRules(locale, PluralRules.PluralType.CARDINAL);
      cachedOrdinalRules = makeRules(locale, PluralRules.PluralType.ORDINAL);
      return (pluralType == PluralRules.PluralType.CARDINAL ? cachedCardinalRules: cachedOrdinalRules);
    }
  }

  private PluralRules makeRules(Locale locale, PluralRules.PluralType pluralType) {
    ListResourceBundle bundle = new LocaleElements_plurals();
    String key = getRuleSetForLanguage(bundle, locale.getLanguage(), pluralType);
    if (key.isEmpty()) {
      return PluralRules.DEFAULT;
    }

    Object[][] allRules = (Object[][]) bundle.getObject("rules");
    for (int i = 0; i < allRules.length; ++i) {
      if (allRules[i][0].equals(key)) {
        return makePluralRules((Object[][]) allRules[i][1]);
      }
    }

    throw new AssertionError("couldn't find " + key + " for " + locale + " " + pluralType);
  }

  private String getRuleSetForLanguage(ListResourceBundle bundle, String languageCode, PluralRules.PluralType type) {
    String key = (type == PluralRules.PluralType.CARDINAL ? "locales" : "locales_ordinals");
    Object[][] map = (Object[][]) bundle.getObject(key);
    for (int i = 0; i < map.length; ++i) {
      if (map[i][0].equals(languageCode)) {
        return (String) map[i][1];
      }
    }
    return ""; // We don't currently need to distinguish between "not found" and "use default".
  }

  private PluralRules makePluralRules(Object[][] ruleData) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < ruleData.length; ++i) {
      if (i > 0) {
        sb.append("; ");
      }
      sb.append(ruleData[i][0]);
      sb.append(':');
      sb.append(ruleData[i][1]);
    }

    try {
      return PluralRules.parseDescription(sb.toString());
    } catch (ParseException ex) {
      throw new AssertionError(ex);
    }
  }
}
