/* GENERATED SOURCE. DO NOT MODIFY. GENERATED BY nfuller @ Mon Oct 05 15:20:14 BST 2015 */
/*
 *******************************************************************************
 * Copyright (C) 2009, International Business Machines Corporation and         *
 * others. All Rights Reserved.                                                *
 *******************************************************************************
 */
package android.icu.impl;

public class ICURegionDataTables extends LocaleDisplayNamesImpl.ICUDataTables {
    public ICURegionDataTables() {
        super(ICUResourceBundle.ICU_REGION_BASE_NAME);
    }
}
