/* GENERATED SOURCE. DO NOT MODIFY. GENERATED BY nfuller @ Mon Oct 05 15:20:14 BST 2015 */
/**
*******************************************************************************
* Copyright (C) 2006-2015, International Business Machines Corporation and
* others. All Rights Reserved.
*******************************************************************************
*
*******************************************************************************
*/ 
package android.icu.impl;

public class InvalidFormatException extends Exception {
    
    // Generated by serialver from JDK 1.4.1_01
    static final long serialVersionUID = 8883328905089345791L;
    
    public InvalidFormatException(){}

    public InvalidFormatException(Throwable cause) {
        super(cause);
    }

    public InvalidFormatException(String message) {
        super(message);
    }
}
