/* GENERATED SOURCE. DO NOT MODIFY. GENERATED BY nfuller @ Mon Oct 05 15:20:14 BST 2015 */
/*
 *******************************************************************************
 * Copyright (C) 1996-2005, International Business Machines Corporation and    *
 * others. All Rights Reserved.                                                *
 *******************************************************************************
 */

package android.icu.impl.data;

import java.util.ListResourceBundle;

public class HolidayBundle_iw extends ListResourceBundle {

    static private final Object[][] fContents = {
        {   "", ""  },      // Can't be empty!
    };

    public synchronized Object[][] getContents() { return fContents; }

}
